output "cluster_endpoint" {
  value       = module.eks.cluster_endpoint
  description = "Endpoint for EKS control plane"
}

output "kubectl_config" {
  value       = module.eks.kubeconfig
  description = "kubectl config as generated by module"
}

output "cluster_security_group_id" {
  value       = module.eks.cluster_security_group_id
  description = "Security grups attached to the cluster control plane"
}

output "region" {
  value       = var.AWS_REGION
  description = "AWS Region"
}

output "cluster_name" {
  value       = var.cluster_name
  description = "Eks cluster name"
}

output "aws_account_id" {
  value       = data.aws_caller_identity.current.account_id
}



