variable "AWS_ACCESS_KEY" {}
variable "AWS_SECRET_KEY" {}
variable "AWS_REGION" {}
variable "cluster_name" {}
variable "k8s_service_account_namespace" {}
variable "k8s_service_account_name" {}
variable "EXTDNS_NAMESPACE" {}
variable "HOSTED_ZONE_NAME" {}
variable "HOSTED_ZONE_IDENTIFIER" {}
variable "SERVICE_TYPE_FILTER" {}
variable "TXT_OWNER_ID" {}